development:
  sessions:
    default:
      database: mallowapp
      hosts:
        - localhost

test:
  sessions:
    default:
      database: mallowapp_test
      hosts:
        - localhost

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
