development:
  sessions:
    default:
      database: mallowapp_development
      hosts:
        - localhost

test:
  sessions:
    default:
      database: mallowapp_test
      hosts:
        - localhost

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
